version: "3.3"
services:
  platform_upravlyaika_bot:
    build: .
    container_name: platform_upravlyaika_bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./source/.env
    depends_on:
      - platform_upravlyaika_cache
    networks:
      - cfu-uprav-platfrorm-bot

  platform_upravlyaika_cache:
    image: redis:alpine
    container_name: platform_upravlyaika_cache
    restart: always
    ports:
      - 11229:6379
    command: redis-server --requirepass ${RS_PASSWORD}
    networks:
      - cfu-uprav-platfrorm-bot
    volumes:
      - cache:/data

volumes:
  cache:

# networks
networks:
  cfu-uprav-platfrorm-bot: