version: "3.3"
services:
  telegram_bot:
    build: .
    image: telegram_bot
    container_name: telegram_bot
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /home/user/.volumes/telegram_bot/source:/source:rw
    tty: true
    working_dir: /source
    command: ["python", "bot.py"]